
{{
  config(
    materialized = 'incremental',
    key='HOST_ID'
    )
}}

Select 
HOST_ID,
REPLACE(HOST_NAME,' ','_') As HOST_NAME,
HOST_SINCE as HOST_SINCE,
IS_SUPERHOST as IS_SUPERHOST,
RESPONSE_RATE as RESPONSE_RATE,
CASE
    WHEN RESPONSE_RATE > 95 THEN 'VERY GOOD'
    WHEN RESPONSE_RATE > 80 THEN 'GOOD'
    WHEN RESPONSE_RATE > 60 THEN 'FAIR'
    ELSE 'POOR'
    END AS RESPONSE_RATE_QUALITY,
    CREATED_AT AS CREATED_AT
FROM 
    {{ ref('bronze_hosts') }}